In [1]:
import numpy as np

In [9]:
x = np.arange(0,21)

In [10]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [11]:
x[8]

8

In [12]:
x[-1]

20

In [13]:
x[13]

13

In [14]:
x[0:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
x[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [17]:
x[2:5]

array([2, 3, 4])

In [18]:
y = x[5:15] = 40

In [19]:
y

40

In [20]:
x

array([ 0,  1,  2,  3,  4, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 15, 16,
       17, 18, 19, 20])

In [22]:
y = x.copy()

In [23]:
y

array([ 0,  1,  2,  3,  4, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 15, 16,
       17, 18, 19, 20])