In [1]:
import numpy as np

In [11]:
x = np.arange(25).reshape(5,5)

In [12]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [13]:
x[2][2]

12

In [14]:
x[4][2]

22

In [15]:
x[4,2]

22

In [16]:
x[0:2,2:]

array([[2, 3, 4],
       [7, 8, 9]])

In [19]:
x[1:4,1:4]

array([[ 6,  7,  8],
       [11, 12, 13],
       [16, 17, 18]])

In [23]:
y = np.arange(1,20)

In [24]:
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [25]:
y>12

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [27]:
y[y>12]

array([13, 14, 15, 16, 17, 18, 19])

In [28]:
y[y<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
y[y%2 == 0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
y[y%2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])