In [1]:
import numpy as np

In [7]:
x = [[[1,2,3],[4,5,6],[2,7,8]],[[3,4,5],[3,6,7],[4,7,8]],[[6,7,8],[2,7,5],[2,6,7]]]
print(x)

[[[1, 2, 3], [4, 5, 6], [2, 7, 8]], [[3, 4, 5], [3, 6, 7], [4, 7, 8]], [[6, 7, 8], [2, 7, 5], [2, 6, 7]]]


In [9]:
y = np.array(x)
print(y)

[[[1 2 3]
  [4 5 6]
  [2 7 8]]

 [[3 4 5]
  [3 6 7]
  [4 7 8]]

 [[6 7 8]
  [2 7 5]
  [2 6 7]]]


# Methods for numpy

In [16]:
x = [1,2,3,4,5]

In [11]:
y = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(x)

array([1, 2, 3, 4])

In [17]:
x

[1, 2, 3, 4, 5]

In [14]:
np.array(y)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
y

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]